### ISSUE TITLE
After update to 4.0.7, NodeMediaServer.on() is not a function

### ISSUE THREAD

**Issue by koko1313** [illuspas/Node-Media-Server#658]
After updating from `v2.7.0` to `v4.0.7`, `nms.on()` functions does not exist:

```javascritp
const nms = new NodeMediaServer(config);

// nms.on is not a function
nms.on('postPublish', (id, streamPath, args) => {
  // ...
}
```

**Comment by illuspas** [comment]
V4 to V2 is incompatible and destructive upgrade, do not exaggerate the version upgrade.

**Comment by koko1313** [comment]
Is `v4` stable, and will documentation be provided for it?

**Comment by illuspas** [comment]
At present, it is still in the development stage, and only the basic functions are satisfied.
The documentation will be written after most of the functions are complete.

**Comment by partharanjan** [comment]
which version of `ffmpeg ` support in `v4`

**Comment by koko1313** [comment]
There are so many unknowns. You should have developed v4 in a new branch, and keep the working version in `master`.

**Comment by partharanjan** [comment]
@illuspas any plan for release?

**Comment by morgansson** [comment]
> There are so many unknowns. You should have developed v4 in a new branch, and keep the working version in `master`.

[Here you go](https://github.com/illuspas/Node-Media-Server/tree/v2)

Regards
